dappx/urls.py
from django.conf.urls import url
from django.urls import path
from dappx import views

app_name = 'dappx'


urlpatterns=[
path('',views.index,name='home'),



path('candidates.html',views.candidates,name='candidates'),

    path('about.html',views.about,name='about'),
    path('contact.html',views.contact,name='contact'),
    path('blog.html',views.blog,name='blog'),
    path('new-post',views.post_job,name='new-post'),
    path('job-post.html',views.find_job,name='job-post'),
path('cand-post',views.find_candidate,name='cand-post'),
    path('blog-single.html',views.blog_single,name='blog-single'),
path('logout',views.logout,name='logout'),
path('login',views.login,name='login'),
path('register',views.register,name='register'),
path('shortlist',views.shortlist,name='shortlist'),
path('message',views.message,name='message'),
]

djangox/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dappx.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/animate.css" %}">

    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">

    <link rel="stylesheet" href="{% static "css/aos.css" %}">
"
    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %}">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %}">


    <link rel="stylesheet" href="{% static "css/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
  </head>
  <body>


    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'dappx:home' %}"">Djungle</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active"><a href="{% url 'dappx:home' %}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="{% url 'dappx:about' %}" class="nav-link">About</a></li>
            <li class="nav-item"><a href="{% url 'dappx:candidates' %}" class="nav-link">Canditates</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'dappx:blog' %}" class="nav-link">Dashboard</a></li>
            {% endif %}

            <li class="nav-item"><a href="{% url 'dappx:contact' %}" class="nav-link">Contact</a></li>
            <li class="nav-item cta mr-md-1"><a href="{% url 'dappx:new-post' %}" class="nav-link">Post a Job</a></li>
            <li class="nav-item cta cta-colored"><a href="{% url 'dappx:job-post' %}" class="nav-link">Want a Job</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item cta cta-colored"><a href="{% url 'dappx:logout' %}" class="nav-link">logout</a></li>
            {% else %}
            <li class="nav-item cta mr-md-1"><a href="{% url 'dappx:login' %}" class="nav-link">login</a></li>
            <li class="nav-item cta cta-colored"><a href="{% url 'dappx:register' %}" class="nav-link">Register</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <!-- END nav -->
    {% block content %}{% endblock %}
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>

  <!-- loader -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    </body>
    </html>