dappx/urls.py
from django.conf.urls import url
from django.urls import path
from dappx import views

app_name = 'dappx'


urlpatterns=[
path('',views.index,name='home'),



path('candidates.html',views.candidates,name='candidates'),

    path('about.html',views.about,name='about'),
    path('contact.html',views.contact,name='contact'),
    path('blog.html',views.blog,name='blog'),
    path('new-post',views.post_job,name='new-post'),
    path('job-post.html',views.find_job,name='job-post'),
path('cand-post',views.find_candidate,name='cand-post'),
    path('blog-single.html',views.blog_single,name='blog-single'),
path('logout',views.logout,name='logout'),
path('login',views.login,name='login'),
path('register',views.register,name='register'),
path('shortlist',views.shortlist,name='shortlist'),
path('message',views.message,name='message'),
]

djangox/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dappx.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dappx/models.py
# dappx/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


# Create your models here.
class Shortlist(models.Model):
    nameofemp = models.CharField(max_length=100)

    name_of_company = models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    stipend=models.IntegerField(default=None)

class postajob(models.Model):
    job_title = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    desc = models.TextField()
    pay = models.IntegerField(default=0)
    JOB_TYPE = (
        ('1', "Full time"),
        ('2', "Part time"),
        ('3', "Internship"),
        ('4', "freelance"),
        ('5', "temporary")
    )

    type = models.CharField(choices=JOB_TYPE, max_length=20)
    field = models.CharField( max_length=20)

    def __str__(self):
        return self.job_title






class candidate_info(models.Model):
    first_name=models.CharField(max_length=100)
    username=models.CharField(max_length=100,default=None)
    user=models.OneToOneField(User,on_delete=models.CASCADE,default=None)
    location=models.CharField(max_length=100)
    college_name=models.CharField(max_length=100)
    JOB_TYPE = (
        ('1', "Full time"),
        ('2', "Part time"),
        ('3', "Internship"),
        ('4', "freelance"),
        ('5', "temporary")
    )
    type=models.CharField(choices=JOB_TYPE,max_length=20,default='3')
    fieldofinterest=models.CharField(max_length=100,default=None)
    cv=models.TextField()
    image=models.ImageField(upload_to='profile_pics',default='media/profile_pic/sam.jpeg')


    def __str__(self):
        return self.first_name




class Blog(models.Model):
    title=models.CharField(max_length=100)
    author=models.CharField(max_length=100)
    desc=models.TextField()
    like=models.IntegerField(default=0)
    def __str__(self):
        return self.title

class Message(models.Model):
    name=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    subject=models.CharField(max_length=100)
    mess=models.TextField()

dappx/forms.py
# dappx/forms.py
from django import forms
from dappx.models import UserProfileInfo
from django.contrib.auth.models import User
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

dappx/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.contrib.auth import authenticate, login, logout
from .models import postajob,candidate_info,Blog,Shortlist,Message


# Create your views here.
def post_job(request):
    if request.method == 'POST':
        newjob = postajob()
        newjob.job_title = request.POST['job_title']
        newjob.field = request.POST['field']
        newjob.company = request.POST['company']
        newjob.location = request.POST['location']
        newjob.desc = request.POST['desc']
        newjob.pay = request.POST['pay']

        newjob.type = request.POST['job-type']
        newjob.save()
        messages.info(request, 'thanks for posting job!!')
        return redirect('/')
    else:
        return render(request, 'dappx/new-post.html')


def find_job(request):
    if request.method == 'POST':
        type = request.POST['job-type']
        location = request.POST['location']
        nameofjob = request.POST['field']

        item = postajob.objects.filter(location=location, type=type, field=nameofjob)
        if item is not None:
           return  render(request, 'dappx/job.html', {'jobs': item})

        else:
            return render(request, 'dappx/job.html', {'jobs': item})
            messages.info(request, 'you will remain jobless forever')
    else :
        return render(request,'dappx/job-post.html')



def find_candidate(request):
    if request.method == 'POST':
        type = request.POST['job-type']
        location = request.POST['location']
        name = request.POST['field']

        item = candidate_info.objects.filter(location=location, type=type,fieldofinterest=name)
        if item is not None:
           return  render(request, 'dappx/profile.html', {'cands': item})
        else:
            messages.info(request, 'cannot find any matching results')
            return render(request, 'dappx/profile.html', {'cand': item})

    else :
        return render(request,'dappx/job-post.html')

def index(request):
    return render(request,'dappx/index.html')
def about(request):
    return render(request,'dappx/about.html')
def blog(request):
    if request.method == 'POST':
        blog1=Blog()
        blog1.title= request.POST['title']
        blog1.author=request.POST['author']
        blog1.desc=request.POST['desc']
        blog1.save()
        return redirect('/')
    else :
        blogs= Blog.objects.all()
        user1=request.user.username
        short =Shortlist.objects.filter(nameofemp=user1)
        context={
            "blogs":blogs,
            "short":short,
        }



        return render(request,'dappx/blog.html',context)



def candidates(request):
    candidate= candidate_info.objects.all()

    return render(request,'dappx/candidates.html',{'cands':candidate})
def blog_single(request):
    return render(request,'dappx/blog-single.html')
def contact(request):
    return render(request,'dappx/contact.html')

def new_post(request):
    return render(request,'dappx/new-post.html')




def register(request):
    if request.method == 'POST':
        username1 = request.POST['user_name']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        password_check = request.POST['password1']


        if password == password_check:
            if User.objects.filter(username=username1).exists():
                messages.info(request,'user already exists')
                return   redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'email already exists')
                return   redirect('/register')
            else :

                user= User.objects.create_user(username=username1,password=password,email=email,first_name=first_name,last_name=last_name)
                user.save();
                cand=candidate_info()
                cand.username=username1
                cand.user=user
                cand.first_name=first_name
                cand.location=request.POST['location']
                cand.type=request.POST['job-type']
                cand.cv=request.POST['cv']
                cand.fieldofinterest=request.POST['field']
                cand.college_name=request.POST['collegename']
                if 'profile_pic' in request.FILES:
                    print('found it')
                    cand.image = request.FILES['profile_pic']
                cand.save()
                print("user created")
                return  redirect('/')

        else :
            messages.info(request, 'passsword not matching')
            return redirect('dappx:register')
    else:

        return render(request,'dappx/register.html')
def login(request):
    if request.method =='POST':
        username1= request.POST['username1']
        password1=request.POST['password']
        user = auth.authenticate(username=username1,password=password1)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else :
            messages.info(request,'invalid credentials')
            return render(request,'dappx/login.html')
    else:
        return render(request,'dappx/login.html')



def logout(request):
    auth.logout(request)
    return redirect('/')


def shortlist(request):

    if request.method == 'POST':
        short=Shortlist()
        short.nameofemp=request.POST['username']
        short.email=request.POST['email']
        short.name_of_company=request.POST['company']
        short.stipend=request.POST['stipend']
        short.save()
        return redirect('/')
    else :
        return render(request,'dappx/shortlist.html')

def message(request):
    m=Message()
    m.name=request.POST['name']
    m.email=request.POST['email']
    m.subject=request.POST['subject']
    m.mess=request.POST['message']
    m.save()
    return redirect('/')

templates/dappx/about.html
{% extends "base.html" %}

{% block content %}


    <div class="hero-wrap hero-wrap-2" style="background-image: url('/static/images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-start">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5">
          	<p class="breadcrumbs mb-0"><span class="mr-3"><a href="{% url "dappx:home" %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>About</span></p>
            <h1 class="mb-3 bread">About Us</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-10">
    				<div class="intro row text-center justify-content-center">
    					<div class="col-md-9">
    						<img class="img-fluid" src="images/undraw_work_time_lhoj.svg" alt="">
    					</div>
    					<h2 class="mb-4">Welcome to Jobpply</h2>
    					<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
    					<p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
    				</div>
    			</div>
    		</div>
    	</div>
    </section>

   	<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url(images/bg_1.jpg);" data-stellar-background-ratio="0.5">
    	<div class="container">
    		<div class="row justify-content-center">
    			<div class="col-md-12">
		    		<div class="row">
		          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center">
		              <div class="text">
		              	<div class="icon">
		              		<span class="flaticon-employee"></span>
		              	</div>
		                <strong class="number" data-number="435000">0</strong>
		                <span>Jobs</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center">
		              <div class="text">
		              	<div class="icon">
		              		<span class="flaticon-collaboration"></span>
		              	</div>
		                <strong class="number" data-number="40000">0</strong>
		                <span>Members</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center">
		              <div class="text">
		              	<div class="icon">
		              		<span class="flaticon-resume"></span>
		              	</div>
		                <strong class="number" data-number="30000">0</strong>
		                <span>Resume</span>
		              </div>
		            </div>
		          </div>
		          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
		            <div class="block-18 text-center">
		              <div class="text">
		              	<div class="icon">
		              		<span class="flaticon-promotions"></span>
		              	</div>
		                <strong class="number" data-number="10500">0</strong>
		                <span>Company</span>
		              </div>
		            </div>
		          </div>
		        </div>
	        </div>
        </div>
    	</div>
    </section>


{% endblock %}

templates/dappx/candidates.html
{% extends "base.html" %}
{% block content %}


    <div class="hero-wrap hero-wrap-2" style="background-image: url('/static/images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-start">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5">
          	<p class="breadcrumbs mb-0"><span class="mr-3"><a href="{% url 'dappx:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Candidates</span></p>
            <h1 class="mb-3 bread">Candidates</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-candidates ftco-candidates-2 bg-light">
    	<div class="container">
    		<div class="row">
				{% for cand in cands %}
        <div class="col-md-6">
         <div class="team d-md-flex">
                 <<img class="img" src="{{ cand.image.url }}">
        			<div class="text pl-md-4">
        				<span class="location mb-0">{{cand.location}}</span>
        				<h2>{{ cand.first_name}}{{ cand.last_name}}</h2>
	        			<span class="position">College : {{cand.college_name}}</span>
	        			<p>{{cand.cv}}</p>
	        			<span class="seen">{{cand.username}}</span>
	        			<p><a href="{% url 'dappx:shortlist' %}" class="btn btn-primary">Shortlist</a></p>
        			</div>
        		</div>
				</div>
					{% endfor %}


          </div>
          </div>
          </section>

    		





{% endblock %}

templates/dappx/job-post.html
{% extends "base.html" %}
{% block content %}



    <div class="hero-wrap hero-wrap-2" style="background-image: url('/static/images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-start">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5">
          	<p class="breadcrumbs mb-0"><span class="mr-3"><a href="{% url 'dappx:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Job Posts</span></p>
            <h1 class="mb-3 bread">Apply Jobs</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section bg-light">
    	<div class="container">
    		<div class="row">
    			<div class="ftco-search">
						<div class="row">
	            <div class="col-md-12 nav-link-wrap">
		            <div class="nav nav-pills text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
		              <a class="nav-link active mr-md-1" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Find a Job</a>

		              <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Find a Candidate</a>

		            </div>
		          </div>
		          <div class="col-md-12 tab-wrap">

		            <div class="tab-content p-4" id="v-pills-tabContent">

		              <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-nextgen-tab">
		              	<form action="job-post.html" class="search-job" method="post">
							{% csrf_token %}
		              		<div class="row no-gutters">
		              			<div class="col-md mr-md-2">
		              				<div class="form-group">
			              				<div class="form-field">
			              					<div class="icon"><span class="icon-briefcase"></span></div>
							                <input type="text" class="form-control" placeholder="eg. Garphic. Web Developer" name="field">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md mr-md-2">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="select-wrap">
					                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
					                     <select id="" class="form-control" name="job-type">
					                      	<option value="Category">Category</option>
					                      	<option value='1'>Full Time</option>
					                        <option value='2'>Part Time</option>
					                        <option value='3'>Freelance</option>
					                        <option value='4'>Internship</option>
					                        <option value='5'>Temporary</option>
					                      </select>
					                    </div>
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md mr-md-2">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="icon"><span class="icon-map-marker"></span></div>
							                <input type="text" class="form-control" placeholder="Location" name="location">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
						                	<button type="submit" class="form-control btn btn-secondary">Search</button>
							              </div>
						              </div>
		              			</div>
		              		</div>
		              	</form>
		              </div>

		              <div class="tab-pane fade" id="v-pills-2" role="tabpanel" aria-labelledby="v-pills-performance-tab">
		              	<form action="cand-post" class="search-job" method="post">
							{% csrf_token %}
		              		<div class="row">
		              			<div class="col-md">
		              				<div class="form-group">
			              				<div class="form-field">
			              					<div class="icon"><span class="icon-user"></span></div>
							                <input type="text" class="form-control" placeholder="field" name="field">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="select-wrap">
					                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
					                      <select id="" class="form-control" name="job-type">
					                      	<option value="category">Category</option>
					                      	<option value='1'>Full Time</option>
					                        <option value='2'>Part Time</option>
					                        <option value='3'>Freelance</option>
					                        <option value='4'>Internship</option>
					                        <option value='5'>Temporary</option>
					                      </select>
					                    </div>
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="icon"><span class="icon-map-marker"></span></div>
							                <input type="text" class="form-control" placeholder="Location" name="location">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
							                <button type="submit" class="form-control btn btn-secondary">Search</button>
							              </div>
						              </div>
		              			</div>
		              		</div>
		              	</form>
		              </div>
		            </div>
		          </div>
		        </div>
	        </div>
    		</div>
    	</div>
    </section>







{% endblock %}

templates/dappx/login.html
{% extends "base.html" %}
{% block content %}

 {% csrf_token %}
    <div class="hero-wrap hero-wrap-2" style="background-image: url('/static/images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-start">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5">
          	<p class="breadcrumbs mb-0"><span class="mr-3"><a href="{% url 'dappx:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Login Page</span></p>
            <h1 class="mb-3 bread">Let's Dive In</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">

			     <form action="login" class="p-5 bg-white" method="POST">
                   {% csrf_token %}


              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Username : </label>
                  <input type="text" id="fullname" class="form-control" placeholder="Username" name="username1">
                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Password : </label>
                  <input type="password" id="fullname" class="form-control" placeholder="Password" name="password">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Login" class="btn btn-primary  py-2 px-5">
                </div>
              </div>


            </form>
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">C.V.Raman Hostel IIT BHU Varanasi</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+919415602019</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
            <p><span>Email:</span> <a href="mailto:chaitanyakumarbansal.cse18@itbhu.ac.in">naveenmall632@gmail.com</a></p>

            </div>

            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">More Info</h3>
              <p>Djungle is the largest job providing in World..</p>
              <p><a href="{% url 'dappx:contact' %}" class="btn btn-primary  py-2 px-4">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>



{% endblock %}

templates/dappx/new-post.html
{% extends "base.html" %}
{% block content %}

 {% csrf_token %}
    <div class="hero-wrap hero-wrap-2" style="background-image: url('/static/images/bg_1.jpg');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-start">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5">
          	<p class="breadcrumbs mb-0"><span class="mr-3"><a href="{% url 'dappx:home' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>New Job Post</span></p>
            <h1 class="mb-3 bread">Post A Job</h1>
          </div>
        </div>
      </div>
    </div>

    <div class="ftco-section bg-light">
      <div class="container">
        <div class="row">

          <div class="col-md-12 col-lg-8 mb-5">

			     <form action="new-post" class="p-5 bg-white" method="post">
                   {% csrf_token %}

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label for="option-price-1">
                    <input type="number" id="option-price-1" name="pay"> <span class="text-success">Stipend </span> For 30 days
                  </label>
                </div>

              </div>

              <div class="row form-group">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Job Title</label>
                  <input type="text" id="fullname" class="form-control" placeholder="eg. Professional UI/UX Designer" name="job_title">
                </div>
              </div>

              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Company</label>
                  <input type="text" id="fullname" class="form-control" placeholder="eg. Facebook, Inc." name="company">
                </div>
              </div>
              <div class="row form-group mb-5">
                <div class="col-md-12 mb-3 mb-md-0">
                  <label class="font-weight-bold" for="fullname">Field </label>
                  <input type="text" id="fullname" class="form-control" placeholder="eg. Facebook, Inc." name="field">
                </div>
              </div>


              <div class="row form-group">
                <div class="col-md-12"><h3>Job Type</h3></div>
                <div class="col-md-12 mb-3 mb-md-0">
                   <select id="fullname" class="form-control" name="job-type">
					                      	<option value="Category">Category</option>
					                      	<option value='1'>Full Time</option>
					                        <option value='2'>Part Time</option>
					                        <option value='3'>Freelance</option>
					                        <option value='4'>Internship</option>
					                        <option value='5'>Temporary</option>
					                      </select>
                </div>

              </div>

              <div class="row form-group mb-4">
                <div class="col-md-12"><h3>Location</h3></div>
                <div class="col-md-12 mb-3 mb-md-0">
                  <input type="text" class="form-control" placeholder="Western City, UK" name="location">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12"><h3>Job Description</h3></div>
                <div class="col-md-12 mb-3 mb-md-0">
                  <input name="desc" class="form-control" id="" cols="30" rows="5">
                </div>
              </div>

              <div class="row form-group">
                <div class="col-md-12">
                  <input type="submit" value="Post" class="btn btn-primary  py-2 px-5">
                </div>
              </div>


            </form>
          </div>

          <div class="col-lg-4">
            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">Contact Info</h3>
              <p class="mb-0 font-weight-bold">Address</p>
              <p class="mb-4">C.V.Raman Hostel IIT BHU Varanasi</p>

              <p class="mb-0 font-weight-bold">Phone</p>
              <p class="mb-4"><a href="#">+919415602019</a></p>

              <p class="mb-0 font-weight-bold">Email Address</p>
            <p><span>Email:</span> <a href="mailto:chaitanyakumarbansal.cse18@itbhu.ac.in">naveenmall632@gmail.com</a></p>

            </div>

            <div class="p-4 mb-3 bg-white">
              <h3 class="h5 text-black mb-3">More Info</h3>
              <p>Djungle is the largest job providing in World..</p>
              <p><a href="{% url 'dappx:contact' %}" class="btn btn-primary  py-2 px-4">Learn More</a></p>
            </div>
          </div>
        </div>
      </div>
      </div>







{% endblock %}